import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SidebarProvider from "@/context/SideBarContext";
import CartProvider from "@/context/CartContext";
import ProductProvider from "@/context/ProductContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <SidebarProvider>
        <CartProvider>
          <ProductProvider>
            <body className={inter.className}>{children}</body>
          </ProductProvider>
        </CartProvider>
      </SidebarProvider>
    </html>
  );
}
